### ISSUE TITLE
Code Review of Tweet Generator Submission 2

### ISSUE THREAD

**Issue by SWHarrison** [kevin-meyers/tweet-generator#2]
- All tests pass with no errors, great job!
- Replace does not work. This is due to using ```==``` instead of assigning a new value to current.data. Additionally, you do not break out of the loop and return, so it will always get to the end of the linked list, see that current is None, and raise an error.
- Correct for all annotations
- Great job completing stretch challenges!

**Comment by kevin-meyers** [comment]
Fixed them!
