### ISSUE TITLE
Tweet Generator Final Project Submission

### ISSUE THREAD

**Issue by Sukhrobjon** [kevin-meyers/tweet-generator#4]
- If you clean your source text from symbols and use regex effectively you will have much better accuracy when generating sentences. 
- `frequency()` method in  `listogram.py` file supposed to return 0 if word not found but you are `rasing value error` which causing the test failing. 
- Also, there might be issue in your  or `add_count()` method. so `test_entries` test is failing
- One of your import files doesn't exist in the folder so I could not run your markov chain locally but seems like it is working on the web. This is the import line
`from data_struct_algo.queues.circular_buffer import CircularBuffer`
- But great work on building nth order markov chain

**Comment by kevin-meyers** [comment]
I'm on my way to fix those bugs right now, and did you install the stuff in the Pipfile? its got everything standard except that line which comes from https://github.com/kevin-meyers/data-struct-algo/blob/master/data_struct_algo/queues/circular_buffer.py
